# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
      
    env:
      SSH_PRIVATE_KEY: ${{ secrets.CIPIPELINE }}
      USERNAME: ${{ secrets.USER_NAME }}
      HOST: ${{ secrets.HOST_NAME}} 

    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2
   
    - name: Deploy to server
      run: echo "$SSH_PRIVATE_KEY" > private_key.pem
    - run: chmod 600 private_key.pem
    - run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST <<EOF
        mkdir -p /home/$USERNAME/app 
        pkill -f "python3 madlibs.py" || true
        mkdir -p /home/$USERNAME/proof
        EOF
    - run: scp -i private_key.pem -o StrictHostKeyChecking=no -r ./* $USERNAME@$HOST:/home/$USERNAME/app
        #ssh -i private_key.pem -o StrictHostKeyChecking=no root@$976bde83453c << EOF
        #cd /home/root/app
        #python3 -m pip install flask
        #nohup python3 madlibs.py >> app.log 2>&1 &
        #disown
        #EOF
